var data = [{
  'name': 'nanka',
  'image': 'assets/images/nanka.jpg',
  'address': 'Jr. Bambues 198, La Molina, Lima 15024, Perú',
  'phone': '+51 1 3697297',
  'attention': '12:30 - 23:30',
  'type': 'Peruana, apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{
  'name': 'panchita',
  'image': 'assets/images/panchita.jpg',
  'address': 'Calle 2 de Mayo 298, Lima, Perú',
  'phone': '+51 1 2425957',
  'attention': '12:00 - 23:00',
  'type': 'Peruana, Latina, Apto para vegetarianos',
  'money': 'S/.65 - S/.82',
},
{
  'name': 'el mercado',
  'image': 'assets/images/el-mercado.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{
  'name': 'madam tusan',
  'image': 'assets/images/madam-tusan.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{
  'name': 'chifa titi',
  'image': 'assets/images/chifa-titi.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{
  'name': 'mr shao',
  'image': 'assets/images/mr-shao.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{ 
  'name': 'rigoletto lima',
  'image': 'assets/images/rigoletto-lima.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{
  'name': 'restaurante rovegno',
  'image': 'assets/images/restaurante-rovegno.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
},
{
  'name': 'morelia',
  'image': 'assets/images/morelia.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Peruana, Latina, Mariscos, Apto para vegetarianos',
  'money': 'Se acepta efectivo y tarjeta visa',
}];