var data = [{
  'name': 'nanka',
  'image': 'assets/images/nanka.jpg',
  'address': 'Jr. Bambues 198, La Molina, Lima 15024, Perú',
  'phone': '+51 1 3697297',
  'attention': '12:30 - 23:30',
  'type': 'Comida Peruana',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/nanka-back.jpg',
},
{
  'name': 'panchita',
  'image': 'assets/images/panchita.jpg',
  'address': 'Calle 2 de Mayo 298, Lima, Perú',
  'phone': '+51 1 2425957',
  'attention': '12:00 - 23:00',
  'type': 'Comida Peruana',
  'money': 'S/.65 - S/.82',
  'back': 'assets/images/panchita-back.svg',
},
{
  'name': 'el mercado',
  'image': 'assets/images/el-mercado.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida Peruana',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/el-mercado-back.jpg',
},
{
  'name': 'madam tusan',
  'image': 'assets/images/madam-tusan.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida China',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/madam-tusan-back.jpg',
},
{
  'name': 'chifa titi',
  'image': 'assets/images/chifa-titi.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida China',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/chifa-titi-back.png',
},
{
  'name': 'mr shao',
  'image': 'assets/images/mr-shao.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida China',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/mr-shao-back.jpg',
},
{ 
  'name': 'rigoletto lima',
  'image': 'assets/images/rigoletto-lima.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida Italiana',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/rigoletto-lima-back.png',
},
{
  'name': 'restaurante rovegno',
  'image': 'assets/images/restaurante-rovegno.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida Italiana',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/restaurante-rovegno-back.png',
},
{
  'name': 'morelia',
  'image': 'assets/images/morelia.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida Italiana',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/morelia-back.png',
},
{
  'name': 'tanta',
  'image': 'assets/images/tanta.jpg',
  'address': 'San Fernando 380 | Esquina Con Vasco Nunez de Balboa, Lima, Perú',
  'phone': '+51 1 6210892',
  'attention': 'Todos los horarios',
  'type': 'Comida Peruana',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/tanta-back.svg',
},
{
  'name': 'la trattoria',
  'image': 'assets/images/la-trattoria.jpg',
  'address': 'Hipolito Unanue 203 Distrito de Miraflores, Lima 15074, Perú',
  'phone': '+51 221 1322',
  'attention': 'Todos los horarios',
  'type': 'Comida Italiana',
  'money': 'Se acepta efectivo y tarjeta visa', 
  'back': 'assets/images/la-trattoria-back.svg',
},
{
  'name': 'china village',
  'image': 'assets/images/china-village.jpg',
  'address': 'San Fernando 380 | Esquina Con Vasco Nunez de Balboa, Lima, Perú',
  'phone': '+51 1 6210892',
  'attention': 'Todos los horarios',
  'type': 'Comida China',
  'money': 'Se acepta efectivo y tarjeta visa',
  'back': 'assets/images/china-village-back.png',
}];